title: Edgard J Cuadra 
logo: "/images/Headshot2.2.jpg?raw=true" 
description: >
  <h4> My Information </h4>
  <a href="https://www.linkedin.com/in/edgardjcuadra/">LinkedIn</a> 
  <br>
  <a href="https://www.GitHub.com/edgardjcuadra/">GitHub</a>  
  <br>
  <br>
  <h4> Contact Information </h4> 
  <p> edgardcuadra8@gmail.com </p>
  <br>
    
theme: jekyll-theme-minimal
