title: Edgard J Cuadra 
logo: "/images/Headshot2.2.jpg?raw=true" 
description: >
  <h4> Contact Information </h4>
  <br>
  <a href="https://www.linkedin.com/in/edgardjcuadra/" class="contact-btn">LinkedIn</a> 
  <br>
  <p> edgardcuadra8@gmail.com </p>
    
theme: jekyll-theme-minimal
