title: Edgard J Cuadra # your name (or website title) here
logo: "/images/Headshot2.2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a style = "font-style: bold"> My Information </a>
  <a href="https://www.linkedin.com/in/edgardjcuadra/">LinkedIn</a> 
  <br>
  <a href="https://www.GitHub.com/edgardjcuadra/">GitHub</a>  
  <br>
  <br>
  <a> Contact Information </a> 
  <br>
  <a> edgardcuadra8@gmail.com </a>
  <br>
    
theme: jekyll-theme-minimal
