title: Edgard J Cuadra # your name (or website title) here
logo: "/images/Headshot2.2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h4> My Information </h4>
  <a href="https://www.linkedin.com/in/edgardjcuadra/">LinkedIn</a> 
  <br>
  <a href="https://www.GitHub.com/edgardjcuadra/">GitHub</a>  
  <br>
  <br>
  <h4> Contact Information </h4> 
  <a> edgardcuadra8@gmail.com </a>
  <br>
    
theme: jekyll-theme-minimal
# Add this section
kramdown:
  syntax_highlighter_opts:
    css_class: 'highlight'
```

3. **Add inline styles** to your template as a quick test to see if styling works:

Create or modify `_layouts/default.html` to include:

````html
<style>
  body {
    background-color: #3B444B !important;
  }
</style>